package authz

import rego.v1

# Generated by scripts/permissions-to-rego.py from changeset `klachten-klachtencoordinator-permission-v10`.

has_role(role) if {
	some r in input.subject.attributes.roles
	r == role
}

has_resource_type(resource_type) if {
	input.resource.type == resource_type
}

has_action(actions) if {
	some a in actions
	input.action.id == a
}

# ---- com.ritense.case.domain.CaseTab -------------------------------------------------------------

klachtencoordinator_case_tab_1 if {
	has_resource_type("com.ritense.case.domain.CaseTab")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_case_tab_1

filter contains {
	"resourceType": "com.ritense.case.domain.CaseTab",
	"actions": ["view"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case.domain.CaseTab")
	has_action(["view"])
}

# ---- com.ritense.case_.domain.definition.CaseDefinition ------------------------------------------

klachtencoordinator_case_definition_1 if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_case_definition_1

filter contains {
	"resourceType": "com.ritense.case_.domain.definition.CaseDefinition",
	"actions": ["view", "view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.key",
			"operator": "in",
			"value": [
				"eerstelijns-klachten",
				"tweedelijns-klachten",
				"interventieverzoek"
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view", "view_list"])
}

# ---- com.ritense.case_.domain.tab.CaseWidgetTabWidget --------------------------------------------

klachtencoordinator_case_widget_tab_widget_1 if {
	has_resource_type("com.ritense.case_.domain.tab.CaseWidgetTabWidget")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_case_widget_tab_widget_1

filter contains {
	"resourceType": "com.ritense.case_.domain.tab.CaseWidgetTabWidget",
	"actions": ["view"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case_.domain.tab.CaseWidgetTabWidget")
	has_action(["view"])
}

# ---- com.ritense.dashboard.domain.Dashboard ------------------------------------------------------

klachtencoordinator_dashboard_1 if {
	has_resource_type("com.ritense.dashboard.domain.Dashboard")
	has_action(["view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_dashboard_1

filter contains {
	"resourceType": "com.ritense.dashboard.domain.Dashboard",
	"actions": ["view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.dashboard.domain.Dashboard")
	has_action(["view", "view_list"])
}

# ---- com.ritense.document.domain.impl.JsonSchemaDocument -----------------------------------------

klachtencoordinator_json_schema_document_1 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign", "assignable", "claim", "modify", "view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_json_schema_document_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assign", "assignable", "claim", "modify", "view", "view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "VTH",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign", "assignable", "claim", "modify", "view", "view_list"])
}

klachtencoordinator_json_schema_document_2 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign", "assignable", "claim", "modify", "view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_json_schema_document_2

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assign", "assignable", "claim", "modify", "view", "view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign", "assignable", "claim", "modify", "view", "view_list"])
}

klachtencoordinator_json_schema_document_3 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign", "assignable", "claim", "modify", "view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_json_schema_document_3

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assign", "assignable", "claim", "modify", "view", "view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "interventieverzoek"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "VTH",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign", "assignable", "claim", "modify", "view", "view_list"])
}

klachtencoordinator_json_schema_document_4 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["create"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_json_schema_document_4

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["create"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "in",
			"value": [
				"eerstelijns-klachten",
				"tweedelijns-klachten",
				"interventieverzoek"
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["create"])
}

klachtencoordinator_json_schema_document_5 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_json_schema_document_5

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assignable"],
	"conditionContainer": {"conditions": [
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "VTH",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
}

# ---- com.ritense.document.domain.impl.JsonSchemaDocumentDefinition -------------------------------

klachtencoordinator_json_schema_document_definition_1 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_json_schema_document_definition_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view", "view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "in",
			"value": [
				"eerstelijns-klachten",
				"tweedelijns-klachten",
				"interventieverzoek"
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view", "view_list"])
}

# ---- com.ritense.document.domain.impl.searchfield.SearchField ------------------------------------

klachtencoordinator_search_field_1 if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_search_field_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.searchfield.SearchField",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.caseDefinitionKey",
			"operator": "in",
			"value": [
				"eerstelijns-klachten",
				"tweedelijns-klachten",
				"interventieverzoek"
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
}

# ---- com.ritense.note.domain.Note ----------------------------------------------------------------

klachtencoordinator_note_1 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["create", "delete", "modify", "view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_note_1

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["create", "delete", "modify", "view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["create", "delete", "modify", "view", "view_list"])
}

# ---- com.ritense.resource.authorization.ResourcePermission ---------------------------------------

klachtencoordinator_resource_permission_1 if {
	has_resource_type("com.ritense.resource.authorization.ResourcePermission")
	has_action(["create", "delete", "modify", "view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_resource_permission_1

filter contains {
	"resourceType": "com.ritense.resource.authorization.ResourcePermission",
	"actions": ["create", "delete", "modify", "view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.resource.authorization.ResourcePermission")
	has_action(["create", "delete", "modify", "view", "view_list"])
}

# ---- com.ritense.valtimo.contract.authentication.User --------------------------------------------

klachtencoordinator_user_1 if {
	has_resource_type("com.ritense.valtimo.contract.authentication.User")
	has_action(["view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_user_1

filter contains {
	"resourceType": "com.ritense.valtimo.contract.authentication.User",
	"actions": ["view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.contract.authentication.User")
	has_action(["view", "view_list"])
}

# ---- com.ritense.valtimo.operaton.domain.OperatonExecution ---------------------------------------

klachtencoordinator_operaton_execution_1 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonExecution")
	has_action(["create"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_operaton_execution_1

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonExecution",
	"actions": ["create"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonExecution")
	has_action(["create"])
}

# ---- com.ritense.valtimo.operaton.domain.OperatonTask --------------------------------------------

klachtencoordinator_operaton_task_1 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assign", "assignable", "claim", "complete", "view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR")
}

allow if klachtencoordinator_operaton_task_1

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["assign", "assignable", "claim", "complete", "view", "view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
			"conditions": [
				{
					"type": "field",
					"field": "documentDefinitionId.name",
					"operator": "in",
					"value": [
						"eerstelijns-klachten",
						"tweedelijns-klachten",
						"interventieverzoek"
					]
				},
				{
					"type": "expression",
					"field": "content.content",
					"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
					"operator": "!=",
					"value": "GGD",
					"clazz": "java.lang.String"
				},
				{
					"type": "expression",
					"field": "content.content",
					"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
					"operator": "!=",
					"value": "VTH",
					"clazz": "java.lang.String"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assign", "assignable", "claim", "complete", "view", "view_list"])
}
