package authz

import rego.v1

# Generated by scripts/permissions-to-rego.py from changeset `eerstelijnsklachten-klachtenbehandelaar-dsb-permission-v4`.

has_role(role) if {
	some r in input.subject.attributes.roles
	r == role
}

has_resource_type(resource_type) if {
	input.resource.type == resource_type
}

has_action(actions) if {
	some a in actions
	input.action.id == a
}

# ---- com.ritense.case.domain.CaseTab -------------------------------------------------------------

klachtbehandelaar_dsb_dienst_stadsbeheer_case_tab_1 if {
	has_resource_type("com.ritense.case.domain.CaseTab")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_case_tab_1

filter contains {
	"resourceType": "com.ritense.case.domain.CaseTab",
	"actions": ["view"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case.domain.CaseTab")
	has_action(["view"])
}

# ---- com.ritense.case_.domain.definition.CaseDefinition ------------------------------------------

klachtbehandelaar_dsb_dienst_stadsbeheer_case_definition_1 if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_case_definition_1

filter contains {
	"resourceType": "com.ritense.case_.domain.definition.CaseDefinition",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.key",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view_list"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_case_definition_2 if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_case_definition_2

filter contains {
	"resourceType": "com.ritense.case_.domain.definition.CaseDefinition",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.key",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view"])
}

# ---- com.ritense.document.domain.impl.JsonSchemaDocument -----------------------------------------

klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_1 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "==",
			"value": "DSB",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_2 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_2

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "==",
			"value": "DSB",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_3 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["modify"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_3

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["modify"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "==",
			"value": "DSB",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["modify"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_4 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["claim"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_4

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["claim"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "==",
			"value": "DSB",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["claim"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_5 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_5

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assign"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "==",
			"value": "DSB",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_6 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_6

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assignable"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "==",
			"value": "DSB",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
}

# ---- com.ritense.document.domain.impl.JsonSchemaDocumentDefinition -------------------------------

klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_definition_1 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_definition_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_definition_2 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_json_schema_document_definition_2

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
}

# ---- com.ritense.document.domain.impl.searchfield.SearchField ------------------------------------

klachtbehandelaar_dsb_dienst_stadsbeheer_search_field_1 if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_search_field_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.searchfield.SearchField",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.caseDefinitionKey",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
}

# ---- com.ritense.note.domain.Note ----------------------------------------------------------------

klachtbehandelaar_dsb_dienst_stadsbeheer_note_1 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_note_1

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
			"conditions": [
				{
					"type": "field",
					"field": "documentDefinitionId.name",
					"operator": "==",
					"value": "eerstelijns-klachten"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["view"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_note_2 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_note_2

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
			"conditions": [
				{
					"type": "field",
					"field": "documentDefinitionId.name",
					"operator": "==",
					"value": "eerstelijns-klachten"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["view_list"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_note_3 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["create"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_note_3

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["create"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
			"conditions": [
				{
					"type": "field",
					"field": "documentDefinitionId.name",
					"operator": "==",
					"value": "eerstelijns-klachten"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["create"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_note_4 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["modify"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_note_4

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["modify"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
			"conditions": [
				{
					"type": "field",
					"field": "documentDefinitionId.name",
					"operator": "==",
					"value": "eerstelijns-klachten"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["modify"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_note_5 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["delete"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_note_5

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["delete"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
			"conditions": [
				{
					"type": "field",
					"field": "documentDefinitionId.name",
					"operator": "==",
					"value": "eerstelijns-klachten"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["delete"])
}

# ---- com.ritense.resource.authorization.ResourcePermission ---------------------------------------

klachtbehandelaar_dsb_dienst_stadsbeheer_resource_permission_1 if {
	has_resource_type("com.ritense.resource.authorization.ResourcePermission")
	has_action(["create", "delete", "modify", "view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_resource_permission_1

filter contains {
	"resourceType": "com.ritense.resource.authorization.ResourcePermission",
	"actions": ["create", "delete", "modify", "view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.resource.authorization.ResourcePermission")
	has_action(["create", "delete", "modify", "view", "view_list"])
}

# ---- com.ritense.valtimo.operaton.domain.OperatonTask --------------------------------------------

klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_1 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_1

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["view_list"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_2 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["complete"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_2

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["complete"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["complete"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_3 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assign"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_3

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["assign"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assign"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_4 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assignable"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_4

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["assignable"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assignable"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_5 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["claim"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_5

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["claim"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["claim"])
}

klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_6 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER")
}

allow if klachtbehandelaar_dsb_dienst_stadsbeheer_operaton_task_6

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTBEHANDELAAR_DSB_DIENST_STADSBEHEER",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["view"])
}
