package authz

import rego.v1

# Generated by scripts/permissions-to-rego.py from changeset `eerstelijnsklachten-medewerker-kcc-permission-v4`.

has_role(role) if {
	some r in input.subject.attributes.roles
	r == role
}

has_resource_type(resource_type) if {
	input.resource.type == resource_type
}

has_action(actions) if {
	some a in actions
	input.action.id == a
}

# ---- com.ritense.case_.domain.definition.CaseDefinition ------------------------------------------

kcc_case_definition_1 if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KCC")
}

allow if kcc_case_definition_1

filter contains {
	"resourceType": "com.ritense.case_.domain.definition.CaseDefinition",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.key",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KCC",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view_list"])
}

kcc_case_definition_2 if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KCC")
}

allow if kcc_case_definition_2

filter contains {
	"resourceType": "com.ritense.case_.domain.definition.CaseDefinition",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.key",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KCC",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view"])
}

# ---- com.ritense.document.domain.impl.JsonSchemaDocument -----------------------------------------

kcc_json_schema_document_1 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KCC")
}

allow if kcc_json_schema_document_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KCC",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
}

# ---- com.ritense.document.domain.impl.JsonSchemaDocumentDefinition -------------------------------

kcc_json_schema_document_definition_1 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KCC")
}

allow if kcc_json_schema_document_definition_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KCC",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
}

kcc_json_schema_document_definition_2 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KCC")
}

allow if kcc_json_schema_document_definition_2

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KCC",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
}

# ---- com.ritense.document.domain.impl.searchfield.SearchField ------------------------------------

kcc_search_field_1 if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KCC")
}

allow if kcc_search_field_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.searchfield.SearchField",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.caseDefinitionKey",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KCC",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
}

# ---- com.ritense.resource.authorization.ResourcePermission ---------------------------------------

kcc_resource_permission_1 if {
	has_resource_type("com.ritense.resource.authorization.ResourcePermission")
	has_action(["view", "view_list"])
	has_role("ROLE_KLACHTEN_KCC")
}

allow if kcc_resource_permission_1

filter contains {
	"resourceType": "com.ritense.resource.authorization.ResourcePermission",
	"actions": ["view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KCC",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.resource.authorization.ResourcePermission")
	has_action(["view", "view_list"])
}
