package authz

import rego.v1

# Generated by scripts/permissions-to-rego.py from changeset `klachten-klachtencoordinator-vth-permission-v7`.

has_role(role) if {
	some r in input.subject.attributes.roles
	r == role
}

has_resource_type(resource_type) if {
	input.resource.type == resource_type
}

has_action(actions) if {
	some a in actions
	input.action.id == a
}

# ---- com.ritense.case.domain.CaseTab -------------------------------------------------------------

klachtencoordinator_vth_case_tab_1 if {
	has_resource_type("com.ritense.case.domain.CaseTab")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_case_tab_1

filter contains {
	"resourceType": "com.ritense.case.domain.CaseTab",
	"actions": ["view"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case.domain.CaseTab")
	has_action(["view"])
}

# ---- com.ritense.case_.domain.definition.CaseDefinition ------------------------------------------

klachtencoordinator_vth_case_definition_1 if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_case_definition_1

filter contains {
	"resourceType": "com.ritense.case_.domain.definition.CaseDefinition",
	"actions": ["view", "view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.key",
			"operator": "in",
			"value": [
				"eerstelijns-klachten",
				"tweedelijns-klachten",
				"interventieverzoek"
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case_.domain.definition.CaseDefinition")
	has_action(["view", "view_list"])
}

# ---- com.ritense.case_.domain.tab.CaseWidgetTabWidget --------------------------------------------

klachtencoordinator_vth_case_widget_tab_widget_1 if {
	has_resource_type("com.ritense.case_.domain.tab.CaseWidgetTabWidget")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_case_widget_tab_widget_1

filter contains {
	"resourceType": "com.ritense.case_.domain.tab.CaseWidgetTabWidget",
	"actions": ["view"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.case_.domain.tab.CaseWidgetTabWidget")
	has_action(["view"])
}

# ---- com.ritense.dashboard.domain.Dashboard ------------------------------------------------------

klachtencoordinator_vth_dashboard_1 if {
	has_resource_type("com.ritense.dashboard.domain.Dashboard")
	has_action(["view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_dashboard_1

filter contains {
	"resourceType": "com.ritense.dashboard.domain.Dashboard",
	"actions": ["view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.dashboard.domain.Dashboard")
	has_action(["view", "view_list"])
}

# ---- com.ritense.document.domain.impl.JsonSchemaDocument -----------------------------------------

klachtencoordinator_vth_json_schema_document_1 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view"])
}

klachtencoordinator_vth_json_schema_document_2 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_2

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view"])
}

klachtencoordinator_vth_json_schema_document_3 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_3

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "interventieverzoek"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view"])
}

klachtencoordinator_vth_json_schema_document_4 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_4

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
}

klachtencoordinator_vth_json_schema_document_5 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_5

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
}

klachtencoordinator_vth_json_schema_document_6 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_6

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "interventieverzoek"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["view_list"])
}

klachtencoordinator_vth_json_schema_document_7 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["create"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_7

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["create"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["create"])
}

klachtencoordinator_vth_json_schema_document_8 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["create"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_8

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["create"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["create"])
}

klachtencoordinator_vth_json_schema_document_9 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["create"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_9

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["create"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "interventieverzoek"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["create"])
}

klachtencoordinator_vth_json_schema_document_10 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["modify"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_10

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["modify"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["modify"])
}

klachtencoordinator_vth_json_schema_document_11 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["modify"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_11

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["modify"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["modify"])
}

klachtencoordinator_vth_json_schema_document_12 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["modify"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_12

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["modify"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "interventieverzoek"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["modify"])
}

klachtencoordinator_vth_json_schema_document_13 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["claim"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_13

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["claim"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["claim"])
}

klachtencoordinator_vth_json_schema_document_14 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["claim"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_14

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["claim"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["claim"])
}

klachtencoordinator_vth_json_schema_document_15 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["claim"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_15

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["claim"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "interventieverzoek"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["claim"])
}

klachtencoordinator_vth_json_schema_document_16 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_16

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assign"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign"])
}

klachtencoordinator_vth_json_schema_document_17 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_17

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assign"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign"])
}

klachtencoordinator_vth_json_schema_document_18 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_18

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assign"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "interventieverzoek"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assign"])
}

klachtencoordinator_vth_json_schema_document_19 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_19

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assignable"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
}

klachtencoordinator_vth_json_schema_document_20 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_20

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assignable"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
}

klachtencoordinator_vth_json_schema_document_21 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_21

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assignable"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "documentDefinitionId.name",
			"operator": "==",
			"value": "interventieverzoek"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.interventieverzoek.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
}

klachtencoordinator_vth_json_schema_document_22 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_22

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocument",
	"actions": ["assignable"],
	"conditionContainer": {"conditions": [
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "OCW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "SZW",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DPZ",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSB",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DSO",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "DBV",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "BSD",
			"clazz": "java.lang.String"
		},
		{
			"type": "expression",
			"field": "content.content",
			"path": "$.rapportageCategorieen.toegewezenDienst.dienst.name",
			"operator": "!=",
			"value": "GGD",
			"clazz": "java.lang.String"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocument")
	has_action(["assignable"])
}

# ---- com.ritense.document.domain.impl.JsonSchemaDocumentDefinition -------------------------------

klachtencoordinator_vth_json_schema_document_definition_1 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_definition_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
}

klachtencoordinator_vth_json_schema_document_definition_2 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_definition_2

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
}

klachtencoordinator_vth_json_schema_document_definition_3 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_definition_3

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "interventieverzoek"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view"])
}

klachtencoordinator_vth_json_schema_document_definition_4 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_definition_4

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
}

klachtencoordinator_vth_json_schema_document_definition_5 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_definition_5

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
}

klachtencoordinator_vth_json_schema_document_definition_6 if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_json_schema_document_definition_6

filter contains {
	"resourceType": "com.ritense.document.domain.impl.JsonSchemaDocumentDefinition",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.name",
			"operator": "==",
			"value": "interventieverzoek"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.JsonSchemaDocumentDefinition")
	has_action(["view_list"])
}

# ---- com.ritense.document.domain.impl.searchfield.SearchField ------------------------------------

klachtencoordinator_vth_search_field_1 if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_search_field_1

filter contains {
	"resourceType": "com.ritense.document.domain.impl.searchfield.SearchField",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.caseDefinitionKey",
			"operator": "==",
			"value": "eerstelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
}

klachtencoordinator_vth_search_field_2 if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_search_field_2

filter contains {
	"resourceType": "com.ritense.document.domain.impl.searchfield.SearchField",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.caseDefinitionKey",
			"operator": "==",
			"value": "tweedelijns-klachten"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
}

klachtencoordinator_vth_search_field_3 if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_search_field_3

filter contains {
	"resourceType": "com.ritense.document.domain.impl.searchfield.SearchField",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "field",
			"field": "id.caseDefinitionKey",
			"operator": "==",
			"value": "interventieverzoek"
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.document.domain.impl.searchfield.SearchField")
	has_action(["view_list"])
}

# ---- com.ritense.note.domain.Note ----------------------------------------------------------------

klachtencoordinator_vth_note_1 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_note_1

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["view"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["view"])
}

klachtencoordinator_vth_note_2 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_note_2

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["view_list"])
}

klachtencoordinator_vth_note_3 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["create"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_note_3

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["create"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["create"])
}

klachtencoordinator_vth_note_4 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["modify"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_note_4

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["modify"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["modify"])
}

klachtencoordinator_vth_note_5 if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["delete"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_note_5

filter contains {
	"resourceType": "com.ritense.note.domain.Note",
	"actions": ["delete"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.note.domain.Note")
	has_action(["delete"])
}

# ---- com.ritense.resource.authorization.ResourcePermission ---------------------------------------

klachtencoordinator_vth_resource_permission_1 if {
	has_resource_type("com.ritense.resource.authorization.ResourcePermission")
	has_action(["create", "delete", "modify", "view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_resource_permission_1

filter contains {
	"resourceType": "com.ritense.resource.authorization.ResourcePermission",
	"actions": ["create", "delete", "modify", "view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.resource.authorization.ResourcePermission")
	has_action(["create", "delete", "modify", "view", "view_list"])
}

# ---- com.ritense.valtimo.contract.authentication.User --------------------------------------------

klachtencoordinator_vth_user_1 if {
	has_resource_type("com.ritense.valtimo.contract.authentication.User")
	has_action(["view", "view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_user_1

filter contains {
	"resourceType": "com.ritense.valtimo.contract.authentication.User",
	"actions": ["view", "view_list"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.contract.authentication.User")
	has_action(["view", "view_list"])
}

# ---- com.ritense.valtimo.operaton.domain.OperatonExecution ---------------------------------------

klachtencoordinator_vth_operaton_execution_1 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonExecution")
	has_action(["create"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_operaton_execution_1

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonExecution",
	"actions": ["create"],
	"conditionContainer": {"conditions": []},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonExecution")
	has_action(["create"])
}

# ---- com.ritense.valtimo.operaton.domain.OperatonTask --------------------------------------------

klachtencoordinator_vth_operaton_task_1 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["view_list"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_operaton_task_1

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["view_list"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["view_list"])
}

klachtencoordinator_vth_operaton_task_2 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["complete"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_operaton_task_2

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["complete"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["complete"])
}

klachtencoordinator_vth_operaton_task_3 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assign"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_operaton_task_3

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["assign"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assign"])
}

klachtencoordinator_vth_operaton_task_4 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assignable"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_operaton_task_4

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["assignable"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["assignable"])
}

klachtencoordinator_vth_operaton_task_5 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["claim"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_operaton_task_5

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["claim"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["claim"])
}

klachtencoordinator_vth_operaton_task_6 if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["view"])
	has_role("ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH")
}

allow if klachtencoordinator_vth_operaton_task_6

filter contains {
	"resourceType": "com.ritense.valtimo.operaton.domain.OperatonTask",
	"actions": ["view"],
	"conditionContainer": {"conditions": [
		{
			"type": "container",
			"resourceType": "com.ritense.valtimo.operaton.domain.OperatonIdentityLink",
			"conditions": [
				{
					"type": "field",
					"field": "groupId",
					"operator": "==",
					"value": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH"
				}
			]
		}
	]},
	"role": "ROLE_KLACHTEN_KLACHTENCOORDINATOR_VTH",
	"contextResourceType": null,
	"contextConditionContainer": {"conditions": []},
} if {
	has_resource_type("com.ritense.valtimo.operaton.domain.OperatonTask")
	has_action(["view"])
}
