#!/usr/bin/env python3
"""Convert Valtimo *.permission.json changesets into Rego policies for the Authorization Manager.

Each permission row becomes a named rule, an `allow if <rule>` and a `filter contains {...}` entry
that echoes the row back in Valtimo's permission format, in the same shape as valtimo.rego.

Usage:
    python3 scripts/permissions-to-rego.py temp/*.permission.json \
        --out docker/openftv-imports/manager/policies --tag klachten
"""

import argparse
import json
import re
import sys
from pathlib import Path

HELPERS = """has_role(role) if {
\tsome r in input.subject.attributes.roles
\tr == role
}

has_resource_type(resource_type) if {
\tinput.resource.type == resource_type
}

has_action(actions) if {
\tsome a in actions
\tinput.action.id == a
}
"""


def dumps(value, indent=""):
    """JSON-encode `value` with tabs, continuing lines at `indent`; valid Rego literal syntax."""
    return json.dumps(value, indent="\t", ensure_ascii=False).replace("\n", "\n" + indent)


def actions_of(permission):
    raw = permission.get("actions", permission.get("action"))
    if raw is None:
        raise ValueError(f"permission without action(s): {permission}")
    if isinstance(raw, str):
        raw = [raw]
    return sorted(set(raw))


def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def role_slug(role_key):
    slug = re.sub(r"^ROLE_(KLACHTEN_)?", "", role_key).lower()
    return re.sub(r"[^a-z0-9]+", "_", slug).strip("_")


def banner(title):
    return f"# ---- {title} ".ljust(100, "-")


def render_permission(rule, permission):
    resource_type = permission["resourceType"]
    role = permission["roleKey"]
    actions = json.dumps(actions_of(permission))
    conditions = dumps(permission.get("conditions", []), "\t")
    return f"""{rule} if {{
\thas_resource_type("{resource_type}")
\thas_action({actions})
\thas_role("{role}")
}}

allow if {rule}

filter contains {{
\t"resourceType": "{resource_type}",
\t"actions": {actions},
\t"conditionContainer": {{"conditions": {conditions}}},
\t"role": "{role}",
\t"contextResourceType": null,
\t"contextConditionContainer": {{"conditions": []}},
}} if {{
\thas_resource_type("{resource_type}")
\thas_action({actions})
}}
"""


def render_policy(changeset):
    changeset_id = changeset.get("changesetId", "")
    groups = {}
    for permission in changeset["permissions"]:
        groups.setdefault(permission["resourceType"], []).append(permission)

    parts = [
        "package authz",
        "",
        "import rego.v1",
        "",
        f"# Generated by scripts/permissions-to-rego.py from changeset `{changeset_id}`.",
        "",
        HELPERS,
    ]
    for resource_type in sorted(groups):
        parts += [banner(resource_type), ""]
        for n, permission in enumerate(groups[resource_type], 1):
            rule = f"{role_slug(permission['roleKey'])}_{snake(resource_type.rsplit('.', 1)[-1])}_{n}"
            parts.append(render_permission(rule, permission))
    return "\n".join(parts)


def render_meta(policy_id, description, tag):
    return (
        f'id: "{policy_id}"\n'
        'language: "rego"\n'
        "metadata:\n"
        f"  description: {json.dumps(description)}\n"
        f'  tags: ["{tag}"]\n'
    )


def write(path, content):
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("inputs", nargs="+", type=Path, help="*.permission.json files")
    parser.add_argument("--out", required=True, type=Path, help="output directory for .rego/.rego.meta files")
    parser.add_argument("--tag", required=True, help="manager tag for the generated policies")
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    for source in sorted(args.inputs):
        name = source.name.removesuffix(".json").removesuffix(".permission")
        changeset = json.loads(source.read_text(encoding="utf-8"))
        write(args.out / f"{name}.rego", render_policy(changeset))
        write(args.out / f"{name}.rego.meta", render_meta(name.replace(".", "-"), changeset.get("changesetId", name), args.tag))

    # `context` is declared with `:=`, so it may exist only once per bundle: it lives in one shared file.
    write(
        args.out / f"{args.tag}.rego",
        "package authz\n\nimport rego.v1\n\n"
        f"# Shared by all `{args.tag}` policies generated by scripts/permissions-to-rego.py.\n\n"
        'context := {\n\t"filter": sort(filter)\n}\n',
    )
    write(args.out / f"{args.tag}.rego.meta", render_meta(args.tag, f"Shared context for the {args.tag} policies", args.tag))


if __name__ == "__main__":
    sys.exit(main())
