---
id: "pdp"
title: "Outway deployment bundle (pdp)"
language: "rego"
tags: ["valtimo", "klachten"]
policies: true
data: true
version: true
targets:
  - uri: "http://openftv-pdp:9443/v1/bundle"
    apikey: ""
    encoding: "bzip2"
